networks:
  mini-data-network:
    driver: bridge

volumes:
  postgres_data:
  minio_data:
  airflow_logs:
  metabase_data:
  shared_logs:

services:

  postgres:
    image: postgres:15
    container_name: mini_postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../database/init:/docker-entrypoint-initdb.d
      - ../logs:/logs
    ports:
      - "5432:5432"
    networks:
      - mini-data-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: mini-minio
    restart: unless-stopped
    env_file:
      - .env
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
      - ../logs:/logs
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - mini-data-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/minio/health/live || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  storage-init:
    build: ../services/storage_init
    container_name: mini-storage-init
    depends_on:
      - minio
    env_file:
      - .env
    environment:
      MINIO_ENDPOINT: minio:9000
    volumes:
      - ../logs:/logs
    networks:
      - mini-data-network
    restart: "no"

  airflow-webserver:
    build:
      context: ../docker/airflow
    container_name: mini-airflow-web
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: ${AIRFLOW_EXECUTOR}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_AIRFLOW_DB}
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_WEBSERVER_SECRET_KEY}
      PYTHONPATH: /opt/airflow/dags
      AIRFLOW__SMTP__SMTP_HOST: smtp.gmail.com
      AIRFLOW__SMTP__SMTP_PORT: 587
      AIRFLOW__SMTP__SMTP_STARTTLS: "True"
      AIRFLOW__SMTP__SMTP_USER: ${SMTP_USER}
      AIRFLOW__SMTP__SMTP_PASSWORD: ${SMTP_PASSWORD}
      AIRFLOW__SMTP__SMTP_MAIL_FROM: ${SMTP_USER}
    volumes:
      - ../pipelines/dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
      - ../logs:/logs
      - ./configs/airflow-init.sh:/airflow-init.sh

    entrypoint: ["/bin/bash", "/airflow-init.sh"]
    command: ["webserver"]
    ports:
      - "8080:8080"
    networks:
      - mini-data-network

  airflow-scheduler:
    build:
      context: ../docker/airflow
    container_name: mini-airflow-scheduler
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: ${AIRFLOW_EXECUTOR}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_AIRFLOW_DB}
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
      PYTHONPATH: /opt/airflow/dags
      AIRFLOW__SMTP__SMTP_HOST: smtp.gmail.com
      AIRFLOW__SMTP__SMTP_PORT: 587
      AIRFLOW__SMTP__SMTP_STARTTLS: "True"
      AIRFLOW__SMTP__SMTP_USER: ${SMTP_USER}
      AIRFLOW__SMTP__SMTP_PASSWORD: ${SMTP_PASSWORD}
      AIRFLOW__SMTP__SMTP_MAIL_FROM: ${SMTP_USER}
    volumes:
      - ../pipelines/dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
      - ../logs:/logs
      - ./configs/airflow-init.sh:/airflow-init.sh

    entrypoint: ["/bin/bash", "/airflow-init.sh"]
    command: ["scheduler"]
    networks:
      - mini-data-network

  data-generator:
    build: ../services/data_generator
    container_name: mini-data-generator
    env_file:
      - .env
    volumes:
      - ../logs:/logs
      - ../storage/sample_data:/data/raw
    networks:
      - mini-data-network
    restart: "no"


  metabase:
    image: metabase/metabase:latest
    container_name: mini-metabase
    restart: unless-stopped
    volumes:
      - metabase_data:/metabase-data
      - ../logs:/logs
    ports:
      - "3000:3000"
    networks:
      - mini-data-network