name: Mini Data Platform CI

on:
  push:
    branches:
      - working_from_home
      - master
  pull_request:
    branches:
      - working_from_home
      - master

jobs:
  build-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file for Docker
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> docker/.env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> docker/.env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> docker/.env
          echo "POSTGRES_AIRFLOW_DB=${{ secrets.POSTGRES_AIRFLOW_DB }}" >> docker/.env
          echo "AIRFLOW_EXECUTOR=${{ secrets.AIRFLOW_EXECUTOR }}" >> docker/.env
          echo "AIRFLOW_FERNET_KEY=${{ secrets.AIRFLOW_FERNET_KEY }}" >> docker/.env
          echo "AIRFLOW_WEBSERVER_SECRET_KEY=${{ secrets.AIRFLOW_WEBSERVER_SECRET_KEY }}" >> docker/.env

      - name: Validate docker-compose file
        run: |
          docker compose -f docker/docker-compose.yml config

      - name: Build Docker images
        run: |
          docker compose -f docker/docker-compose.yml build --no-cache

      - name: Start services
        run: |
          docker compose -f docker/docker-compose.yml up -d

      - name: Wait for Postgres to be healthy
        run: |
          for i in {1..20}; do
            if docker exec mini_postgres pg_isready -U ${{ secrets.POSTGRES_USER }}; then
              echo "Postgres is ready"
              break
            fi
            echo "Waiting for Postgres..."
            sleep 5
          done

      - name: Initialize Airflow DB
        run: |
          docker exec mini-airflow-web airflow db init

      - name: Upload test CSV to MinIO
        run: |
          docker exec mini-minio mc alias set local http://localhost:9000 ${{ secrets.POSTGRES_USER }} ${{ secrets.POSTGRES_PASSWORD }}
        
      - name: Create test CSV inside Airflow container
        run: |
          docker exec mini-airflow-web bash -c "
          cat <<EOF > /tmp/test_sales.csv
            order_code,customer_code,customer_name,email,country,product_code,quantity,unit_price,total_price
            ORD001,CUST001,John Doe,john@example.com,Ghana,PROD001,2,50,100
            EOF
            "

      - name: Upload test CSV to sales-raw bucket
        run: |
          docker exec mini-airflow-web python - <<EOF
            from minio import Minio
            client = Minio("mini-minio:9000",
                access_key="${{ secrets.POSTGRES_USER }}",
                secret_key="${{ secrets.POSTGRES_PASSWORD }}",
                secure=False
            )
            client.fput_object("sales-raw", "ci_test.csv", "/tmp/test_sales.csv")
            print("Upload successful")
            EOF

      - name: Trigger ETL DAG
        run: |
          docker exec mini-airflow-web airflow dags trigger sales_etl_pipeline

      - name: Wait for DAG execution
        run: sleep 60

      - name: Validate Airflow DAG import
        run: |
          docker exec mini-airflow-web airflow dags list

    
      - name: Wait for MinIO to be healthy
        run: |
          for i in {1..20}; do
            if docker exec mini-minio curl -f http://localhost:9000/minio/health/live; then
              echo "MinIO is ready"
              break
            fi
            echo "Waiting for MinIO..."
            sleep 5
          done

      - name: Validate data inserted into Postgres
        run: |
          docker exec mini_postgres psql -U ${{ secrets.POSTGRES_USER }} -d ${{ secrets.POSTGRES_DB }} -c "SELECT COUNT(*) FROM fact_sales;" > result.txt
          cat result.txt
          if ! grep -q "1" result.txt; then
            echo "Data validation failed"
            exit 1
          fi

      - name: Tear down containers
        if: always()
        run: |
          docker compose -f docker/docker-compose.yml down -v